// MMO_ECS_SERVER - Jed Fakhfekh - https://github.com/ougi-washi

#pragma once

// SERVER
#define MAX_SHARD_COUNT_PER_SERVER 5
#define MAX_SERVERS_COUNT 100
#define SERVER_TICK_RATE 500.f

// SHARD
#define SHARD_TICK_RATE 200.f
#define MAX_ACTOR_COUNT_PER_SHARD 1000
#define MAX_PLAYER_COUNT_PER_SHARD 500
#define MAX_NON_PLAYER_COUNT_PER_SHARD 500
#define MAX_SUB_SERVER_COUNT_PER_SHARD 10

// ARCHIVE
#define MAX_ARCHIVE_DATA_COUNT 64
#define MAX_ARCHIVE_DATA_SIZE 1024

// NETWORK
#define UDP_LISTENING_PORT 3726

// RPC
#define MAX_FUNCTION_NAME_SIZE 256
#define MAX_FUNCTION_OWNER_SIZE 256
#define MAX_CLIENT_ID_SIZE 8
#define MAX_CLIENT_HASH_SIZE 8